package teko.ch.zigbee.HueGUI;

import com.fasterxml.jackson.databind.JsonNode;
import teko.ch.zigbee.baseApi.ConfigManager;
import teko.ch.zigbee.baseApi.HueBridgeController;
import teko.ch.zigbee.baseApi.hueBridgeConnector;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;

public class HueGui extends JPanel {
    private JPanel HueGui;
    private JButton ButtonToConnect;

    public HueGui() {
        this.setLayout(new BorderLayout()); // Set the layout manager to BorderLayout
        // ... (Initialize your components)
        this.add(HueGui, BorderLayout.CENTER);
        initComponents();
        ButtonToConnect.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                ScheduledExecutorService executorService = Executors.newSingleThreadScheduledExecutor();
                String configFilePath = "config.txt";
                Map<String, String> configData = new HashMap<>();
                Map<String, String> readData = ConfigManager.readConfig(configFilePath);


                String ipAddress = readData.get("IP");
                String bridgeKey = readData.get("Key");
                hueBridgeConnector connector = new hueBridgeConnector();

                if (ipAddress == null && bridgeKey == null) {
                    ipAddress = hueBridgeConnector.getMyIP();
                    try {
                        bridgeKey = connector.getKey();
                    } catch (IOException ex) {
                        throw new RuntimeException(ex);
                    }

                    configData.put("IP", ipAddress);
                    configData.put("Key", bridgeKey);

                    Runnable task = () -> ConfigManager.writeConfig(configFilePath, configData);

                    executorService.schedule(task, 2, TimeUnit.SECONDS);


                }
                String bridgeBaseUrl = "http://" + ipAddress + "/api/"; // Replace with your Hue Bridge base URL

                HueBridgeController controller = new HueBridgeController(bridgeBaseUrl, bridgeKey);



                System.out.println("finish");
                try {
                    controller.setLampState(1, "on", "true");
                    controller.setLampState(1, "xyz", "[0.00,0.00,0.00]");


                    controller.getLampState(1);
                    JsonNode jsonResponse = controller.getAllLamps();
                    System.out.println(jsonResponse.toString());




                } catch (IOException ex) {
                    ex.printStackTrace();
                }
            }
        });
    }

    private void initComponents() {
        // This method will be automatically generated by IntelliJ IDEA
        // It will initialize components based on the .form file
    }


}
