package teko.ch.zigbee.HueGUI;

import javax.swing.*;
import java.awt.*;

public class HueGui extends JPanel {
    private JPanel HueGui;
    private JPanel Panel;
    private JButton connectToYourHueButton;
    private JFormattedTextField welcomeToOurPhilipsFormattedTextField;
    private JFormattedTextField connectHereToYourFormattedTextField;

    public HueGui() {
        this.setLayout(new BorderLayout()); // Set the layout manager to BorderLayout
        // ... (Initialize your components)
        this.add(HueGui, BorderLayout.CENTER);
        initComponents();
    }

    private void initComponents() {
        // This method will be automatically generated by IntelliJ IDEA
        // It will initialize components based on the .form file
    }

}
